//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wifi.AutoVerwaltung.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FormMainLocation {
            get {
                return ((global::System.Drawing.Point)(this["FormMainLocation"]));
            }
            set {
                this["FormMainLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1800, 900")]
        public global::System.Drawing.Size FormMainSize {
            get {
                return ((global::System.Drawing.Size)(this["FormMainSize"]));
            }
            set {
                this["FormMainSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FormMainState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FormMainState"]));
            }
            set {
                this["FormMainState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewMainColumnMarke {
            get {
                return ((int)(this["ListViewMainColumnMarke"]));
            }
            set {
                this["ListViewMainColumnMarke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewMainColumnModell {
            get {
                return ((int)(this["ListViewMainColumnModell"]));
            }
            set {
                this["ListViewMainColumnModell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewMainColumnFarbe {
            get {
                return ((int)(this["ListViewMainColumnFarbe"]));
            }
            set {
                this["ListViewMainColumnFarbe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewMainColumnErstzulassung {
            get {
                return ((int)(this["ListViewMainColumnErstzulassung"]));
            }
            set {
                this["ListViewMainColumnErstzulassung"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("187")]
        public int ListViewMainColumnGesamtkosten {
            get {
                return ((int)(this["ListViewMainColumnGesamtkosten"]));
            }
            set {
                this["ListViewMainColumnGesamtkosten"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int splitContainer1SplitterDistance {
            get {
                return ((int)(this["splitContainer1SplitterDistance"]));
            }
            set {
                this["splitContainer1SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FormEditLocation {
            get {
                return ((global::System.Drawing.Point)(this["FormEditLocation"]));
            }
            set {
                this["FormEditLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1600, 850")]
        public global::System.Drawing.Size FormEditSize {
            get {
                return ((global::System.Drawing.Size)(this["FormEditSize"]));
            }
            set {
                this["FormEditSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FormEditState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FormEditState"]));
            }
            set {
                this["FormEditState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FormTankLocation {
            get {
                return ((global::System.Drawing.Point)(this["FormTankLocation"]));
            }
            set {
                this["FormTankLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("760, 240")]
        public global::System.Drawing.Size FormTankSize {
            get {
                return ((global::System.Drawing.Size)(this["FormTankSize"]));
            }
            set {
                this["FormTankSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FormTankState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FormTankState"]));
            }
            set {
                this["FormTankState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FormKostenLocation {
            get {
                return ((global::System.Drawing.Point)(this["FormKostenLocation"]));
            }
            set {
                this["FormKostenLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1600, 240")]
        public global::System.Drawing.Size FormKostenSize {
            get {
                return ((global::System.Drawing.Size)(this["FormKostenSize"]));
            }
            set {
                this["FormKostenSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FormKostenState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FormKostenState"]));
            }
            set {
                this["FormKostenState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewKostenColumnKategorie {
            get {
                return ((int)(this["ListViewKostenColumnKategorie"]));
            }
            set {
                this["ListViewKostenColumnKategorie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewKostenColumnDatum {
            get {
                return ((int)(this["ListViewKostenColumnDatum"]));
            }
            set {
                this["ListViewKostenColumnDatum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewKostenColumnKosten {
            get {
                return ((int)(this["ListViewKostenColumnKosten"]));
            }
            set {
                this["ListViewKostenColumnKosten"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewKostenColumnKilometer {
            get {
                return ((int)(this["ListViewKostenColumnKilometer"]));
            }
            set {
                this["ListViewKostenColumnKilometer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewKostenColumnZahlweise {
            get {
                return ((int)(this["ListViewKostenColumnZahlweise"]));
            }
            set {
                this["ListViewKostenColumnZahlweise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewKostenColumnBemerkung {
            get {
                return ((int)(this["ListViewKostenColumnBemerkung"]));
            }
            set {
                this["ListViewKostenColumnBemerkung"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewTankColumnBetrag {
            get {
                return ((int)(this["ListViewTankColumnBetrag"]));
            }
            set {
                this["ListViewTankColumnBetrag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewTankColumnDatum {
            get {
                return ((int)(this["ListViewTankColumnDatum"]));
            }
            set {
                this["ListViewTankColumnDatum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewTankColumnMenge {
            get {
                return ((int)(this["ListViewTankColumnMenge"]));
            }
            set {
                this["ListViewTankColumnMenge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewTankColumnKilometer {
            get {
                return ((int)(this["ListViewTankColumnKilometer"]));
            }
            set {
                this["ListViewTankColumnKilometer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewTankColumnStreckeGefahren {
            get {
                return ((int)(this["ListViewTankColumnStreckeGefahren"]));
            }
            set {
                this["ListViewTankColumnStreckeGefahren"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ListViewTankColumnVerbrauch {
            get {
                return ((int)(this["ListViewTankColumnVerbrauch"]));
            }
            set {
                this["ListViewTankColumnVerbrauch"] = value;
            }
        }
    }
}
